#!/bin/bash
# Runs after 01_schema.sql. Loads the CSVs generated by source/generate.py.
# Skips silently if you have not run the generator yet.
set -e
[ -f /seed/dark_stores.csv ] || { echo ">> /seed empty, run generate.py then restart"; exit 0; }

for t in dark_stores customers products riders inventory orders order_items; do
  echo ">> loading $t"
  psql -v ON_ERROR_STOP=1 -U postgres -d qcommerce \
    -c "\copy qc.$t FROM '/seed/$t.csv' WITH (FORMAT csv, HEADER true, NULL '')"
done

psql -U postgres -d qcommerce -c "
  SELECT 'dark_stores' t, COUNT(*) FROM qc.dark_stores
  UNION ALL SELECT 'customers',   COUNT(*) FROM qc.customers
  UNION ALL SELECT 'products',    COUNT(*) FROM qc.products
  UNION ALL SELECT 'riders',      COUNT(*) FROM qc.riders
  UNION ALL SELECT 'inventory',   COUNT(*) FROM qc.inventory
  UNION ALL SELECT 'orders',      COUNT(*) FROM qc.orders
  UNION ALL SELECT 'order_items', COUNT(*) FROM qc.order_items;"
