#!/usr/bin/env bash
# =============================================================================
# scripts/p7_cdc_sink.sh — land the seven CDC topics into RAW.
#
# Part 3 consumed exactly one topic, qc.order_status, and that topic is hand
# produced rather than captured. The seven Debezium topics -- the actual tables
# of the operational database -- have been sitting in the broker unconsumed
# since Part 3. CORE cannot conform a customer dimension that does not exist,
# so this is Part 7's prerequisite, not new scope.
#
# A SECOND connector, not an edit to the first. Connect derives the consumer
# group from the connector name, so this one gets its own group and its own
# offsets, and mechanism 1's benchmark tables are left exactly as measured.
# Editing the existing connector would have rewritten the thing being compared.
#
# The value is the FULL Debezium envelope. debezium-postgres.json sets no
# ExtractNewRecordState transform, so each record is
#   { "before": {...}|null, "after": {...}|null, "op": "r|c|u|d",
#     "source": {...}, "ts_ms": ... }
# That before-image is the whole reason CDC beats a nightly extract for SCD2,
# and unwrapping it at ingest would throw away the only copy.
#
# The POST response from Connect echoes the full config back, private key
# included. Nothing in this script prints that response raw -- the key is
# redacted before anything reaches stdout. A key in scrollback is a leaked key.
#
#   bash scripts/p7_cdc_sink.sh diagnose  where the data actually is. Read-only
#   bash scripts/p7_cdc_sink.sh resnapshot force Debezium to snapshot again
#   bash scripts/p7_cdc_sink.sh check     topic sizes, register nothing
#   bash scripts/p7_cdc_sink.sh create    register the sink
#   bash scripts/p7_cdc_sink.sh status
#   bash scripts/p7_cdc_sink.sh delete
#
# COST: streams ~171,000 rows on Snowpipe Streaming. Serverless, so RM_POC
# cannot see it. Estimate 0.02-0.05 credits, UNVERIFIED -- the Part 3 figure
# was never measured because the credits backfill has not been run.
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")/.."

ACCOUNT="AWTTGVH-OLB61128.snowflakecomputing.com:443"
USER="SVC_KAFKA"
ROLE="QC_LOADER"
DB="QCOMMERCE"
SCHEMA="RAW"
KEYFILE="${KEYFILE:-rsa_kafka.p8}"
CONNECT="localhost:8083"
NAME="qc-snowflake-cdc-v4"

# Topic -> table. Explicit, so no autogenerated name sanitization runs and the
# CDC_ prefix keeps these visibly distinct from the conformed CORE tables.
TOPICS="qc.dark_stores,qc.customers,qc.products,qc.riders,qc.inventory,qc.orders,qc.order_items"
MAP="qc.dark_stores:CDC_DARK_STORES,qc.customers:CDC_CUSTOMERS,qc.products:CDC_PRODUCTS,qc.riders:CDC_RIDERS,qc.inventory:CDC_INVENTORY,qc.orders:CDC_ORDERS,qc.order_items:CDC_ORDER_ITEMS"

# Topic depth, summed across partitions. Parsed by HEADER NAME, not by field
# position: rpk's column layout varies with version and whether the ERROR
# column is populated, and `awk '{print $NF}'` silently reported 0 for topics
# that were full -- a zero that looked exactly like an empty topic.
depth() {
  docker exec qc-redpanda rpk topic describe -p "$1" 2>/dev/null | python3 -c '
import sys
col = None
total = 0
seen = False
for line in sys.stdin:
    f = line.split()
    if not f:
        continue
    if "LOG-END-OFFSET" in f:
        col = f.index("LOG-END-OFFSET")
        continue
    if col is not None and f[0].isdigit() and len(f) > col:
        try:
            total += int(f[col]); seen = True
        except ValueError:
            pass
print(total if seen else -1)
'
}

cmd="${1:-diagnose}"

case "$cmd" in
diagnose)
  # Read-only. Answers one question in order: is the data in Postgres, is it in
  # the broker, and is the connector doing anything about it.
  echo "== 1. Postgres — does the source still hold the rows?"
  docker exec qc-postgres psql -U postgres -d qcommerce -tA -c "
    SELECT 'dark_stores', COUNT(*) FROM qc.dark_stores
    UNION ALL SELECT 'customers',   COUNT(*) FROM qc.customers
    UNION ALL SELECT 'products',    COUNT(*) FROM qc.products
    UNION ALL SELECT 'riders',      COUNT(*) FROM qc.riders
    UNION ALL SELECT 'inventory',   COUNT(*) FROM qc.inventory
    UNION ALL SELECT 'orders',      COUNT(*) FROM qc.orders
    UNION ALL SELECT 'order_items', COUNT(*) FROM qc.order_items;" \
    2>/dev/null || echo "  could not query qc schema"

  echo
  echo "== 2. Broker — which topics exist"
  docker exec qc-redpanda rpk topic list

  echo
  echo "== 3. Replication slot and publication"
  # A slot that exists with no Connect offsets is the state that matters: the
  # slot holds a WAL position, but Debezium decides whether to snapshot from
  # ITS OWN offsets, and _connect_offsets is absent. Dropping the slot makes
  # that unambiguous rather than relying on it.
  docker exec qc-postgres psql -U postgres -d qcommerce -c \
    "SELECT slot_name, plugin, active, restart_lsn FROM pg_replication_slots;" 2>/dev/null
  docker exec qc-postgres psql -U postgres -d qcommerce -c \
    "SELECT pubname FROM pg_publication;" 2>/dev/null

  echo "== 4. Connectors registered"
  curl -s "$CONNECT/connectors" | python3 -m json.tool
  echo
  echo "== 5. Why the source connector is not producing"
  # UNASSIGNED means the worker has not given the connector to anyone. The task
  # underneath can still report RUNNING, which is the same green-status-field
  # lie this project has hit at every stage.
  docker logs qc-connect 2>&1 | grep -iE "qc-postgres-cdc|snapshot|replication slot|ERROR" \
    | tail -20 || true
  ;;

resnapshot)
  # DESTRUCTIVE on the local stack only: deletes the source connector and drops
  # its replication slot so Debezium starts clean. Postgres table data is not
  # touched. Nothing in Azure or Snowflake is touched.
  echo "== deleting the source connector"
  curl -s -X DELETE "$CONNECT/connectors/qc-postgres-cdc" || true
  sleep 3

  echo "== dropping the replication slot so snapshot.mode=initial actually snapshots"
  docker exec qc-postgres psql -U postgres -d qcommerce -c \
    "SELECT pg_drop_replication_slot(slot_name) FROM pg_replication_slots WHERE slot_name = 'qc_slot';"

  echo "== re-registering Debezium"
  curl -s -X POST -H "Content-Type: application/json" \
       --data @source/connectors/debezium-postgres.json \
       "$CONNECT/connectors" | python3 -m json.tool

  echo
  echo "Snapshotting 171,403 rows takes a minute or two. Then:"
  echo "  bash scripts/p7_cdc_sink.sh check"
  ;;

check)
  echo "== Debezium topics and their depths"
  # High watermark per partition. A topic at 0 means the snapshot never ran or
  # the volume was destroyed -- register nothing until this looks right.
  # Per topic, so one missing topic does not abort the whole report. rpk exits
  # nonzero on UNKNOWN_TOPIC_OR_PARTITION, which would otherwise hide the rest.
  for t in $(echo "$TOPICS" | tr ',' ' '); do
    d=$(depth "$t")
    if [ "$d" = "-1" ]; then printf "  %-20s MISSING\n" "$t"
    else                     printf "  %-20s %s records\n" "$t" "$d"; fi
  done
  echo
  echo "  (RAW=1 to print rpk's own output instead of a parsed depth)"
  if [ "${RAW:-0}" = "1" ]; then
    for t in $(echo "$TOPICS" | tr ',' ' '); do
      echo; echo "--- $t"
      docker exec qc-redpanda rpk topic describe -p "$t" 2>&1 | head -8
    done
  fi
  echo
  echo "Expect roughly: dark_stores 8 · customers 500 · products 200 · riders 60"
  echo "                inventory 96,000 · orders 20,000 · order_items 54,635"
  echo
  echo "Source connector state:"
  curl -s "$CONNECT/connectors/qc-postgres-cdc/status" | python3 -m json.tool 2>/dev/null \
    || echo "  qc-postgres-cdc not registered"
  ;;

create)
  [ -f "$KEYFILE" ] || { echo "$KEYFILE not found in repo root"; exit 1; }
  KEY=$(grep -v "^-----" "$KEYFILE" | tr -d '\n')

  # Key read at submit time and inlined into the POST body, never written to a
  # file in this repo. Same handling as p3_sink.sh.
  cat > /tmp/qc-cdc-sink.json <<JSON
{
  "name": "$NAME",
  "config": {
    "connector.class": "com.snowflake.kafka.connector.SnowflakeStreamingSinkConnector",
    "tasks.max": "3",
    "topics": "$TOPICS",
    "snowflake.topic2table.map": "$MAP",
    "snowflake.url.name": "$ACCOUNT",
    "snowflake.user.name": "$USER",
    "snowflake.role.name": "$ROLE",
    "snowflake.private.key": "$KEY",
    "snowflake.database.name": "$DB",
    "snowflake.schema.name": "$SCHEMA",
    "snowflake.enable.schematization": "false",
    "snowflake.streaming.classic.offset.migration": "skip",
    "snowflake.streaming.validate.compatibility.with.classic": "false",
    "snowflake.validation": "server_side",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false"
  }
}
JSON
  # REDACTED. Connect echoes the whole config back on a successful POST,
  # including snowflake.private.key. Piping that to stdout puts the private key
  # in terminal scrollback, in any screenshot, and in anything the output is
  # pasted into. Nothing prints the response raw.
  curl -s -X POST -H "Content-Type: application/json" \
       --data @/tmp/qc-cdc-sink.json "$CONNECT/connectors" \
    | python3 -c '
import json, sys
try:
    r = json.load(sys.stdin)
except Exception:
    print("non-JSON response from Connect; check: docker logs qc-connect"); raise SystemExit(1)
if "error_code" in r:
    print("FAILED", r.get("error_code"), r.get("message", "")[:400]); raise SystemExit(1)
cfg = r.get("config", {})
for k in list(cfg):
    if "private" in k or "password" in k or "secret" in k:
        cfg[k] = "<redacted, %d chars>" % len(cfg[k])
print("registered:", r.get("name"))
print("  topics :", cfg.get("topics", "")[:120])
print("  tables :", cfg.get("snowflake.topic2table.map", "")[:200])
print("  key    :", cfg.get("snowflake.private.key"))
'
  rm -f /tmp/qc-cdc-sink.json
  echo
  echo "Give it a minute, then: bash scripts/p7_cdc_sink.sh status"
  ;;

status)
  curl -s "$CONNECT/connectors/$NAME/status" | python3 -m json.tool
  echo
  # RUNNING on an empty topic is the green status field this project has been
  # burned by every time. Lag is the number that means something.
  echo "== consumer lag (the number that matters, not the RUNNING state)"
  docker exec qc-redpanda rpk group describe "connect-$NAME" 2>/dev/null \
    || echo "  group not formed yet"
  ;;

delete)
  curl -s -X DELETE "$CONNECT/connectors/$NAME" && echo "deleted $NAME"
  ;;

*) echo "usage: $0 diagnose|resnapshot|check|create|status|delete"; exit 1 ;;
esac
