#!/usr/bin/env bash
# =============================================================================
# scripts/p7_cdc_sink.sh — land the seven CDC topics into RAW.
#
# Part 3 consumed exactly one topic, qc.order_status, and that topic is hand
# produced rather than captured. The seven Debezium topics -- the actual tables
# of the operational database -- have been sitting in the broker unconsumed
# since Part 3. CORE cannot conform a customer dimension that does not exist,
# so this is Part 7's prerequisite, not new scope.
#
# A SECOND connector, not an edit to the first. Connect derives the consumer
# group from the connector name, so this one gets its own group and its own
# offsets, and mechanism 1's benchmark tables are left exactly as measured.
# Editing the existing connector would have rewritten the thing being compared.
#
# The value is the FULL Debezium envelope. debezium-postgres.json sets no
# ExtractNewRecordState transform, so each record is
#   { "before": {...}|null, "after": {...}|null, "op": "r|c|u|d",
#     "source": {...}, "ts_ms": ... }
# That before-image is the whole reason CDC beats a nightly extract for SCD2,
# and unwrapping it at ingest would throw away the only copy.
#
#   bash scripts/p7_cdc_sink.sh check     topic sizes, register nothing
#   bash scripts/p7_cdc_sink.sh create    register the sink
#   bash scripts/p7_cdc_sink.sh status
#   bash scripts/p7_cdc_sink.sh delete
#
# COST: streams ~171,000 rows on Snowpipe Streaming. Serverless, so RM_POC
# cannot see it. Estimate 0.02-0.05 credits, UNVERIFIED -- the Part 3 figure
# was never measured because the credits backfill has not been run.
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")/.."

ACCOUNT="AWTTGVH-OLB61128.snowflakecomputing.com:443"
USER="SVC_KAFKA"
ROLE="QC_LOADER"
DB="QCOMMERCE"
SCHEMA="RAW"
KEYFILE="${KEYFILE:-rsa_kafka.p8}"
CONNECT="localhost:8083"
NAME="qc-snowflake-cdc-v4"

# Topic -> table. Explicit, so no autogenerated name sanitization runs and the
# CDC_ prefix keeps these visibly distinct from the conformed CORE tables.
TOPICS="qc.dark_stores,qc.customers,qc.products,qc.riders,qc.inventory,qc.orders,qc.order_items"
MAP="qc.dark_stores:CDC_DARK_STORES,qc.customers:CDC_CUSTOMERS,qc.products:CDC_PRODUCTS,qc.riders:CDC_RIDERS,qc.inventory:CDC_INVENTORY,qc.orders:CDC_ORDERS,qc.order_items:CDC_ORDER_ITEMS"

cmd="${1:-check}"

case "$cmd" in
check)
  echo "== Debezium topics and their depths"
  # High watermark per partition. A topic at 0 means the snapshot never ran or
  # the volume was destroyed -- register nothing until this looks right.
  docker exec qc-redpanda rpk topic describe -p $(echo "$TOPICS" | tr ',' ' ') 2>/dev/null \
    || docker exec qc-redpanda rpk topic list
  echo
  echo "Expect roughly: dark_stores 8 · customers 500 · products 200 · riders 60"
  echo "                inventory 96,000 · orders 20,000 · order_items 54,635"
  echo
  echo "Source connector state:"
  curl -s "$CONNECT/connectors/qc-postgres-cdc/status" | python3 -m json.tool 2>/dev/null \
    || echo "  qc-postgres-cdc not registered"
  ;;

create)
  [ -f "$KEYFILE" ] || { echo "$KEYFILE not found in repo root"; exit 1; }
  KEY=$(grep -v "^-----" "$KEYFILE" | tr -d '\n')

  # Key read at submit time and inlined into the POST body, never written to a
  # file in this repo. Same handling as p3_sink.sh.
  cat > /tmp/qc-cdc-sink.json <<JSON
{
  "name": "$NAME",
  "config": {
    "connector.class": "com.snowflake.kafka.connector.SnowflakeStreamingSinkConnector",
    "tasks.max": "3",
    "topics": "$TOPICS",
    "snowflake.topic2table.map": "$MAP",
    "snowflake.url.name": "$ACCOUNT",
    "snowflake.user.name": "$USER",
    "snowflake.role.name": "$ROLE",
    "snowflake.private.key": "$KEY",
    "snowflake.database.name": "$DB",
    "snowflake.schema.name": "$SCHEMA",
    "snowflake.enable.schematization": "false",
    "snowflake.streaming.classic.offset.migration": "skip",
    "snowflake.streaming.validate.compatibility.with.classic": "false",
    "snowflake.validation": "server_side",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false"
  }
}
JSON
  curl -s -X POST -H "Content-Type: application/json" \
       --data @/tmp/qc-cdc-sink.json "$CONNECT/connectors" | python3 -m json.tool
  rm -f /tmp/qc-cdc-sink.json
  echo
  echo "Give it a minute, then: bash scripts/p7_cdc_sink.sh status"
  ;;

status)
  curl -s "$CONNECT/connectors/$NAME/status" | python3 -m json.tool
  echo
  # RUNNING on an empty topic is the green status field this project has been
  # burned by every time. Lag is the number that means something.
  echo "== consumer lag (the number that matters, not the RUNNING state)"
  docker exec qc-redpanda rpk group describe "connect-$NAME" 2>/dev/null \
    || echo "  group not formed yet"
  ;;

delete)
  curl -s -X DELETE "$CONNECT/connectors/$NAME" && echo "deleted $NAME"
  ;;

*) echo "usage: $0 check|create|status|delete"; exit 1 ;;
esac
