-- sql/p0_probe.sql  —  PART 0 FEATURE PROBE (generated by scripts/gen_p0_probe.py)
-- =============================================================================
-- READ-ONLY. Creates nothing, alters nothing, drops nothing.
-- Run in a Snowsight worksheet as ACCOUNTADMIN. Paste the output back.
--
-- COST: needs an XS warehouse running for ~2-4 minutes.
--       Warehouse:  ~0.03-0.07 credits.
--       Cortex:     ~11 single-row AI calls, tokens are trivial; well inside the
--                   ~10 credit/day trial AI cap. UNVERIFIED but not a risk here.
--
-- ORDER: run SECTION 1, then SECTION 2, then SECTION 3. Paste all three outputs.
-- =============================================================================

ALTER SESSION SET QUERY_TAG = 'p00:probe';

-- =============================================================================
-- SECTION 1 — identity and account shape. Cannot fail. Run All is safe here.
-- =============================================================================
SELECT CURRENT_ORGANIZATION_NAME()  AS org,
       CURRENT_ACCOUNT()            AS account,
       CURRENT_REGION()             AS region,
       CURRENT_VERSION()            AS sf_version,
       CURRENT_ROLE()               AS role,
       CURRENT_WAREHOUSE()          AS wh,
       CURRENT_TIMESTAMP()          AS probed_at;

-- Credits consumed so far.
SELECT SUM(credits_used) AS credits_used_to_date
FROM   SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY;

-- -----------------------------------------------------------------------------
-- SECTION 1b — OPTIONAL, run separately. Needs ORGADMIN. If USE ROLE ORGADMIN is
-- rejected, skip the rest of 1b and read the edition off Snowsight ->
-- Admin -> Accounts instead. Do not let this abort the run.
-- -----------------------------------------------------------------------------
USE ROLE ORGADMIN;
SHOW ORGANIZATION ACCOUNTS;
SELECT "account_name", "edition", "snowflake_region", "created_on", "account_url"
FROM   TABLE(RESULT_SCAN(LAST_QUERY_ID()));
USE ROLE ACCOUNTADMIN;

-- =============================================================================
-- SECTION 2 — object-surface probes. SHOW never errors on a missing feature,
-- it returns zero rows, so Run All is safe for this whole section.
-- Record ROW COUNT and whether the command itself was rejected.
-- =============================================================================
SHOW WAREHOUSES;
SHOW RESOURCE MONITORS;
SHOW INTEGRATIONS;
SHOW EXTERNAL VOLUMES;
SHOW DYNAMIC TABLES IN ACCOUNT;
SHOW ICEBERG TABLES IN ACCOUNT;
SHOW HYBRID TABLES IN ACCOUNT;
SHOW STREAMLITS IN ACCOUNT;
SHOW CORTEX SEARCH SERVICES IN ACCOUNT;
SHOW SEMANTIC VIEWS IN ACCOUNT;
SHOW AGENTS IN ACCOUNT;                    -- Snowflake CoWork agents
SHOW GIT REPOSITORIES IN ACCOUNT;
SHOW DBT PROJECTS IN ACCOUNT;
SHOW APPLICATION PACKAGES;
SHOW MANAGED ACCOUNTS;                     -- reader accounts
SHOW SHARES;
SHOW TAGS IN ACCOUNT;
SHOW ALERTS IN ACCOUNT;
SHOW NOTEBOOKS IN ACCOUNT;
SHOW CLASSES IN SNOWFLAKE.ML;              -- FORECAST / ANOMALY_DETECTION / TOP_INSIGHTS
SHOW FUNCTIONS LIKE 'AI\\_%' IN SCHEMA SNOWFLAKE.CORTEX;
SHOW DATABASE ROLES IN DATABASE SNOWFLAKE; -- expect CORTEX_USER / AI_FUNCTIONS_USER

-- AISQL needs the USE AI FUNCTIONS account privilege (granted to PUBLIC by
-- default) PLUS the CORTEX_USER or AI_FUNCTIONS_USER database role.
SHOW GRANTS TO ROLE PUBLIC;
SELECT "privilege", "granted_on", "name"
FROM   TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE  "privilege" ILIKE '%AI%' OR "name" ILIKE '%CORTEX%';
SHOW GRANTS TO ROLE ACCOUNTADMIN;
SELECT "privilege", "granted_on", "name"
FROM   TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE  "privilege" ILIKE '%AI%' OR "name" ILIKE '%CORTEX%';

-- =============================================================================
-- SECTION 3 — function probes. A missing function is a COMPILE error, so each
-- probe is wrapped in its own exception block. This whole section is ONE
-- statement: put the cursor in it and run it once.
--
-- Output is a single text cell, one line per probe: name=VERDICT|detail
-- Copy the whole cell and paste it back.
--
-- If this block itself errors (Snowflake Scripting is not enabled, or a syntax
-- rejection), fall back to sql/p0_probe_flat.sql and run those one-liners
-- individually.
-- =============================================================================
EXECUTE IMMEDIATE $$
DECLARE
  r STRING DEFAULT '';
BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'WITH a AS (SELECT 1 k, TO_TIMESTAMP_NTZ(0) t), b AS (SELECT 1 k, TO_TIMESTAMP_NTZ(0) t) SELECT COUNT(*) FROM a ASOF JOIN b MATCH_CONDITION(a.t >= b.t) ON a.k = b.k';
    r := r || 'sql.asof_join=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'sql.asof_join=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM (SELECT 1 id, 1 v UNION ALL SELECT 1, 2) MATCH_RECOGNIZE(PARTITION BY id ORDER BY v MEASURES COUNT(*) c ONE ROW PER MATCH PATTERN(x+) DEFINE x AS TRUE)';
    r := r || 'sql.match_recognize=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'sql.match_recognize=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT ST_DISTANCE(TO_GEOGRAPHY(''POINT(77.02 28.45)''), TO_GEOGRAPHY(''POINT(77.03 28.46)''))';
    r := r || 'sql.geography_st_distance=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'sql.geography_st_distance=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT ST_DWITHIN(TO_GEOGRAPHY(''POINT(77.02 28.45)''), TO_GEOGRAPHY(''POINT(77.03 28.46)''), 5000)';
    r := r || 'sql.st_dwithin=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'sql.st_dwithin=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT H3_LATLNG_TO_CELL(28.45, 77.02, 8)';
    r := r || 'sql.h3_latlng_to_cell=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'sql.h3_latlng_to_cell=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT ARRAY_SIZE(H3_GRID_DISK(H3_LATLNG_TO_CELL(28.45,77.02,8), 1))';
    r := r || 'sql.h3_grid_disk=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'sql.h3_grid_disk=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT H3_CELL_TO_BOUNDARY(H3_LATLNG_TO_CELL(28.45,77.02,8))';
    r := r || 'sql.h3_cell_to_boundary=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'sql.h3_cell_to_boundary=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT [1,2,3]::VECTOR(FLOAT,3)';
    r := r || 'sql.vector_type=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'sql.vector_type=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT VECTOR_COSINE_SIMILARITY([1,2,3]::VECTOR(FLOAT,3), [1,2,4]::VECTOR(FLOAT,3))';
    r := r || 'sql.vector_cosine=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'sql.vector_cosine=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT * FROM (SELECT 1 x) QUALIFY ROW_NUMBER() OVER (ORDER BY x) = 1';
    r := r || 'sql.qualify=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'sql.qualify=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM (SELECT SEQ4() s, UNIFORM(0,1,RANDOM()) u FROM TABLE(GENERATOR(ROWCOUNT => 10)))';
    r := r || 'sql.generator_uniform=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'sql.generator_uniform=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'WITH RECURSIVE t(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM t WHERE n < 3) SELECT COUNT(*) FROM t';
    r := r || 'sql.recursive_cte=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'sql.recursive_cte=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM (SELECT SEQ4() s FROM TABLE(GENERATOR(ROWCOUNT=>100))) SAMPLE (10 ROWS)';
    r := r || 'sql.tablesample=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'sql.tablesample=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT LEFT(AI_COMPLETE(''claude-4-sonnet'', ''say ok''), 20)';
    r := r || 'cortex.ai_complete=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'cortex.ai_complete=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT AI_CLASSIFY(''parcel arrived late'', [''DELIVERY'',''QUALITY''])';
    r := r || 'cortex.ai_classify=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'cortex.ai_classify=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT AI_FILTER(''is this about delivery: parcel late'')';
    r := r || 'cortex.ai_filter=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'cortex.ai_filter=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT AI_AGG(c, ''summarise in five words'') FROM (SELECT ''late parcel'' c UNION ALL SELECT ''cold food'')';
    r := r || 'cortex.ai_agg=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'cortex.ai_agg=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT AI_SUMMARIZE_AGG(c) FROM (SELECT ''late parcel'' c UNION ALL SELECT ''cold food'')';
    r := r || 'cortex.ai_summarize_agg=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'cortex.ai_summarize_agg=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT AI_EXTRACT(text => ''order 918273 was late'', responseFormat => {''order_id'': ''the order number''})';
    r := r || 'cortex.ai_extract=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'cortex.ai_extract=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT AI_SIMILARITY(''late parcel'', ''parcel was late'')';
    r := r || 'cortex.ai_similarity=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'cortex.ai_similarity=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT ARRAY_SIZE(AI_EMBED(''snowflake-arctic-embed-m-v1.5'', ''late'')::ARRAY)';
    r := r || 'cortex.ai_embed=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'cortex.ai_embed=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT SNOWFLAKE.CORTEX.SENTIMENT(''the parcel was very late'')';
    r := r || 'cortex.sentiment=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'cortex.sentiment=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT ARRAY_SIZE(SNOWFLAKE.CORTEX.EMBED_TEXT_768(''snowflake-arctic-embed-m'', ''late'')::ARRAY)';
    r := r || 'cortex.embed_text_768=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'cortex.embed_text_768=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT LEFT(SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'', ''say ok''), 20)';
    r := r || 'cortex.complete_legacy=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'cortex.complete_legacy=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES LIMIT 1';
    r := r || 'meta.object_dependencies=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'meta.object_dependencies=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_ATTRIBUTION_HISTORY LIMIT 1';
    r := r || 'meta.query_attribution_history=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'meta.query_attribution_history=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY LIMIT 1';
    r := r || 'meta.warehouse_metering=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'meta.warehouse_metering=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY LIMIT 1';
    r := r || 'meta.metering_history=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'meta.metering_history=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM SNOWFLAKE.ORGANIZATION_USAGE.USAGE_IN_CURRENCY_DAILY LIMIT 1';
    r := r || 'meta.organization_usage=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'meta.organization_usage=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM SNOWFLAKE.INFORMATION_SCHEMA.DATABASES';
    r := r || 'meta.information_schema=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'meta.information_schema=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY LIMIT 1';
    r := r || 'meta.access_history_absent_expected=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'meta.access_history_absent_expected=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM SNOWFLAKE.ACCOUNT_USAGE.MATERIALIZED_VIEW_REFRESH_HISTORY LIMIT 1';
    r := r || 'gate.materialized_view_expect_fail=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'gate.materialized_view_expect_fail=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  BEGIN
    EXECUTE IMMEDIATE 'SHOW DATA METRIC FUNCTIONS IN ACCOUNT';
    r := r || 'gate.data_metric_functions_expect_fail=OK\n';
  EXCEPTION WHEN OTHER THEN
    r := r || 'gate.data_metric_functions_expect_fail=FAIL|' || REPLACE(LEFT(SQLERRM, 140), '\n', ' ') || '\n';
  END;
  RETURN r;
END;
$$;
